// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Course.proto

package com.jin.proto;

public interface CourseReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.CourseReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
