// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Course.proto

package com.jin.proto;

public final class Course {
  private Course() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_CourseReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_CourseReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_CourseRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_CourseRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Course.proto\022\rcom.jin.proto\"\027\n\tCourseR" +
      "eq\022\n\n\002id\030\001 \001(\005\"\031\n\tCourseRes\022\014\n\004name\030\001 \001(" +
      "\t2V\n\rCourseService\022E\n\rgetCourseById\022\030.co" +
      "m.jin.proto.CourseReq\032\030.com.jin.proto.Co" +
      "urseRes\"\000B\031\n\rcom.jin.protoB\006CourseP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jin_proto_CourseReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jin_proto_CourseReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_CourseReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_jin_proto_CourseRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jin_proto_CourseRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_CourseRes_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
